INSERT INTO Country VALUES(1, 'usa', 1)
INSERT INTO Country VALUES(2, 'germany', 2)
INSERT INTO Country VALUES(3, 'france', 2)
INSERT INTO Country VALUES(4, 'japan', 3)
INSERT INTO Country VALUES(5, 'italy', 2)
INSERT INTO Country VALUES(6, 'sweden', 2)
INSERT INTO Country VALUES(7, 'uk', 2)
INSERT INTO Country VALUES(8, 'korea', 3)
INSERT INTO Country VALUES(9, 'russia', 2)
INSERT INTO Country VALUES(10, 'nigeria', 4)
INSERT INTO Country VALUES(11, 'australia', 5)
INSERT INTO Country VALUES(12, 'new zealand', 5)
INSERT INTO Country VALUES(13, 'egypt', 4)
INSERT INTO Country VALUES(14, 'mexico', 1)
INSERT INTO Country VALUES(15, 'brazil', 1)
