CREATE TABLE Appelations (
No INT,
Appelation VARCHAR(255),
County VARCHAR(255),
State VARCHAR(255),
Area VARCHAR(255),
isAVA VARCHAR(255)
);

CREATE TABLE Grapes (
ID INT,
Grape VARCHAR(255),
Color VARCHAR(255)
);

CREATE TABLE Wine (
No Int,
Grape VARCHAR(255),
Winery VARCHAR(255),
Appelation VARCHAR(255),
State VARCHAR(255),
Name VARCHAR(255),
Year INT,
Price INT,
Score INT,
CASES INT,
Drink VARCHAR(255)
);